FROM node:14-alpine

RUN npm install -g typescript
RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node package*.json ./
USER node
RUN npm install
COPY --chown=node:node . .
EXPOSE 8000

CMD ["npm", "run", "dev"]