// export enum ActionType {
//     SIGN_IN_START = 'SIGN_IN_START',
//     SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
//     SIGN_IN_FAILURE = 'SIGN_IN_FAILURE',
//     SIGN_UP_START = 'SIGN_UP_START',
//     SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
//     SIGN_UP_FAILURE = 'SIGN_UP_FAILURE',
//     FETCH_ME_START = 'FETCH_ME_START',
//     FETCH_ME_SUCCESS = 'FETCH_ME_SUCCESS',
//     FETCH_ME_FAILURE = 'FETCH_ME_FAILURE',
//     SIGN_OUT = 'SIGN_OUT'
// }


export enum ActionType {
    USER_REQUEST_START = 'USER_REQUEST_START',
    USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS',
    USER_REQUEST_FAILURE = 'USER_REQUEST_FAILURE',
    SIGN_OUT = 'SIGN_OUT'
}